/*CREATE TABLE INSPISESSION
(
  SESS_ID        VARCHAR(32)              NOT NULL
  CONSTRAINT INSPISESSIONID_PK
  PRIMARY KEY,
  SESS_SEC_LEVEL NUMBER(3) DEFAULT 255    NOT NULL,
  SESS_CREATED   NUMBER(11) DEFAULT 0     NOT NULL,
  SESS_EXPIRY    NUMBER(11) DEFAULT 0     NOT NULL,
  SESS_TIMEOUT   NUMBER(11) DEFAULT 0     NOT NULL,
  SESS_LOCKED    NUMBER(1) DEFAULT 1      NOT NULL,
  SESS_VALUE     CLOB        DEFAULT '',
  SESS_ENC_IV    VARCHAR(32) DEFAULT '',
  SESS_SEC_ID    VARCHAR(32) DEFAULT ''   NOT NULL,
  SESS_TRACE     VARCHAR(4000) DEFAULT '' NOT NULL
)
  /

COMMENT ON TABLE INSPISESSION IS 'This table stores PHP session data'
  /*/

DROP TABLE IF EXISTS `INSPISESSION`;
CREATE TABLE `INSPISESSION` (
  `SESS_ID` varchar(32) binary NOT NULL DEFAULT '',
  `SESS_SEC_LEVEL` int(3) unsigned NOT NULL DEFAULT 255,
  `SESS_CREATED` int(11) NOT NULL DEFAULT 0,
  `SESS_EXPIRY` int(11) NOT NULL DEFAULT 0,
  `SESS_TIMEOUT` int(11) NOT NULL DEFAULT 0,
  `SESS_LOCKED` int(1) NOT NULL DEFAULT 1,
  `SESS_VALUE` BLOB,
  `SESS_ENC_IV` VARCHAR(32) NOT NULL DEFAULT '',
  `SESS_SEC_ID` VARCHAR(32) NOT NULL DEFAULT '',
  `SESS_TRACE` VARCHAR(4000) NOT NULL DEFAULT '',
  PRIMARY KEY  (`SESS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci
  COMMENT = 'NDB_TABLE=READ_BACKUP=0,PARTITION_BALANCE=FOR_RP_BY_NODE';
